# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quotecast/pb/quotecast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='quotecast/pb/quotecast.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cquotecast/pb/quotecast.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"v\n\x08Metadata\x12\x35\n\x11response_datetime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x10request_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xed\x02\n\tQuotecast\x12\x11\n\tjson_data\x18\x01 \x01(\t\x12\x1b\n\x08metadata\x18\x02 \x01(\x0b\x32\t.Metadata\x1a\xaf\x02\n\x07Request\x12<\n\rsubscriptions\x18\x01 \x03(\x0b\x32%.Quotecast.Request.SubscriptionsEntry\x12@\n\x0funsubscriptions\x18\x02 \x03(\x0b\x32\'.Quotecast.Request.UnsubscriptionsEntry\x1aP\n\x12SubscriptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.ListValue:\x02\x38\x01\x1aR\n\x14UnsubscriptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.ListValue:\x02\x38\x01\"\x90\x02\n\x06Ticker\x12\x1b\n\x08metadata\x18\x01 \x01(\x0b\x32\t.Metadata\x12\'\n\x08products\x18\x02 \x03(\x0b\x32\x15.Ticker.ProductsEntry\x12\x14\n\x0cproduct_list\x18\x03 \x03(\t\x1ah\n\x07Metrics\x12-\n\x07metrics\x18\x01 \x03(\x0b\x32\x1c.Ticker.Metrics.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a@\n\rProductsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.Ticker.Metrics:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_datetime', full_name='Metadata.response_datetime', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_duration', full_name='Metadata.request_duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=245,
)


_QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY = _descriptor.Descriptor(
  name='SubscriptionsEntry',
  full_name='Quotecast.Request.SubscriptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Quotecast.Request.SubscriptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Quotecast.Request.SubscriptionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=529,
)

_QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY = _descriptor.Descriptor(
  name='UnsubscriptionsEntry',
  full_name='Quotecast.Request.UnsubscriptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Quotecast.Request.UnsubscriptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Quotecast.Request.UnsubscriptionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=613,
)

_QUOTECAST_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Quotecast.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriptions', full_name='Quotecast.Request.subscriptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsubscriptions', full_name='Quotecast.Request.unsubscriptions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY, _QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=613,
)

_QUOTECAST = _descriptor.Descriptor(
  name='Quotecast',
  full_name='Quotecast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_data', full_name='Quotecast.json_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='Quotecast.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUOTECAST_REQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=613,
)


_TICKER_METRICS_METRICSENTRY = _descriptor.Descriptor(
  name='MetricsEntry',
  full_name='Ticker.Metrics.MetricsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Ticker.Metrics.MetricsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Ticker.Metrics.MetricsEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=822,
)

_TICKER_METRICS = _descriptor.Descriptor(
  name='Metrics',
  full_name='Ticker.Metrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='Ticker.Metrics.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TICKER_METRICS_METRICSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=822,
)

_TICKER_PRODUCTSENTRY = _descriptor.Descriptor(
  name='ProductsEntry',
  full_name='Ticker.ProductsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Ticker.ProductsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Ticker.ProductsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=824,
  serialized_end=888,
)

_TICKER = _descriptor.Descriptor(
  name='Ticker',
  full_name='Ticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='Ticker.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='products', full_name='Ticker.products', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_list', full_name='Ticker.product_list', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TICKER_METRICS, _TICKER_PRODUCTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=888,
)

_METADATA.fields_by_name['response_datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METADATA.fields_by_name['request_duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY.containing_type = _QUOTECAST_REQUEST
_QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY.containing_type = _QUOTECAST_REQUEST
_QUOTECAST_REQUEST.fields_by_name['subscriptions'].message_type = _QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY
_QUOTECAST_REQUEST.fields_by_name['unsubscriptions'].message_type = _QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY
_QUOTECAST_REQUEST.containing_type = _QUOTECAST
_QUOTECAST.fields_by_name['metadata'].message_type = _METADATA
_TICKER_METRICS_METRICSENTRY.containing_type = _TICKER_METRICS
_TICKER_METRICS.fields_by_name['metrics'].message_type = _TICKER_METRICS_METRICSENTRY
_TICKER_METRICS.containing_type = _TICKER
_TICKER_PRODUCTSENTRY.fields_by_name['value'].message_type = _TICKER_METRICS
_TICKER_PRODUCTSENTRY.containing_type = _TICKER
_TICKER.fields_by_name['metadata'].message_type = _METADATA
_TICKER.fields_by_name['products'].message_type = _TICKER_PRODUCTSENTRY
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['Quotecast'] = _QUOTECAST
DESCRIPTOR.message_types_by_name['Ticker'] = _TICKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'quotecast.pb.quotecast_pb2'
  # @@protoc_insertion_point(class_scope:Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Quotecast = _reflection.GeneratedProtocolMessageType('Quotecast', (_message.Message,), {

  'Request' : _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

    'SubscriptionsEntry' : _reflection.GeneratedProtocolMessageType('SubscriptionsEntry', (_message.Message,), {
      'DESCRIPTOR' : _QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY,
      '__module__' : 'quotecast.pb.quotecast_pb2'
      # @@protoc_insertion_point(class_scope:Quotecast.Request.SubscriptionsEntry)
      })
    ,

    'UnsubscriptionsEntry' : _reflection.GeneratedProtocolMessageType('UnsubscriptionsEntry', (_message.Message,), {
      'DESCRIPTOR' : _QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY,
      '__module__' : 'quotecast.pb.quotecast_pb2'
      # @@protoc_insertion_point(class_scope:Quotecast.Request.UnsubscriptionsEntry)
      })
    ,
    'DESCRIPTOR' : _QUOTECAST_REQUEST,
    '__module__' : 'quotecast.pb.quotecast_pb2'
    # @@protoc_insertion_point(class_scope:Quotecast.Request)
    })
  ,
  'DESCRIPTOR' : _QUOTECAST,
  '__module__' : 'quotecast.pb.quotecast_pb2'
  # @@protoc_insertion_point(class_scope:Quotecast)
  })
_sym_db.RegisterMessage(Quotecast)
_sym_db.RegisterMessage(Quotecast.Request)
_sym_db.RegisterMessage(Quotecast.Request.SubscriptionsEntry)
_sym_db.RegisterMessage(Quotecast.Request.UnsubscriptionsEntry)

Ticker = _reflection.GeneratedProtocolMessageType('Ticker', (_message.Message,), {

  'Metrics' : _reflection.GeneratedProtocolMessageType('Metrics', (_message.Message,), {

    'MetricsEntry' : _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), {
      'DESCRIPTOR' : _TICKER_METRICS_METRICSENTRY,
      '__module__' : 'quotecast.pb.quotecast_pb2'
      # @@protoc_insertion_point(class_scope:Ticker.Metrics.MetricsEntry)
      })
    ,
    'DESCRIPTOR' : _TICKER_METRICS,
    '__module__' : 'quotecast.pb.quotecast_pb2'
    # @@protoc_insertion_point(class_scope:Ticker.Metrics)
    })
  ,

  'ProductsEntry' : _reflection.GeneratedProtocolMessageType('ProductsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TICKER_PRODUCTSENTRY,
    '__module__' : 'quotecast.pb.quotecast_pb2'
    # @@protoc_insertion_point(class_scope:Ticker.ProductsEntry)
    })
  ,
  'DESCRIPTOR' : _TICKER,
  '__module__' : 'quotecast.pb.quotecast_pb2'
  # @@protoc_insertion_point(class_scope:Ticker)
  })
_sym_db.RegisterMessage(Ticker)
_sym_db.RegisterMessage(Ticker.Metrics)
_sym_db.RegisterMessage(Ticker.Metrics.MetricsEntry)
_sym_db.RegisterMessage(Ticker.ProductsEntry)


_QUOTECAST_REQUEST_SUBSCRIPTIONSENTRY._options = None
_QUOTECAST_REQUEST_UNSUBSCRIPTIONSENTRY._options = None
_TICKER_METRICS_METRICSENTRY._options = None
_TICKER_PRODUCTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
