class URLs:
    ACCOUNT_OVERVIEW = 'https://trader.degiro.nl/reporting/secure/v6/accountoverview'
    CLIENT_DETAILS = 'https://trader.degiro.nl/pa/secure/client'
    CLIENT_INFO = 'https://trader.degiro.nl/trading/secure/v5/account/info'
    CONFIG = 'https://trader.degiro.nl/login/secure/config'
    LOGIN ='https://trader.degiro.nl/login/secure/login'
    ORDER_CHECK = 'https://trader.degiro.nl/trading/secure/v5/checkOrder'
    ORDER_CONFIRM = 'https://trader.degiro.nl/trading/secure/v5/order'
    ORDER_DELETE = 'https://trader.degiro.nl/trading/secure/v5/order'
    ORDERS_HISTORY = 'https://trader.degiro.nl/reporting/secure/v4/order-history'
    ORDER_UPDATE = 'https://trader.degiro.nl/trading/secure/v5/order'
    TRANSACTIONS_HISTORY = 'https://trader.degiro.nl/reporting/secure/v4/transactions'
    UPDATE = 'https://trader.degiro.nl/trading/secure/v5/update'