class URLs:
    ACCOUNT_OVERVIEW = 'https://trader.degiro.nl/reporting/secure/v6/accountoverview'
    CLIENT_DETAILS = 'https://trader.degiro.nl/pa/secure/client'
    CLIENT_INFO = 'https://trader.degiro.nl/trading/secure/v5/account/info'
    CONFIG = 'https://trader.degiro.nl/login/secure/config'
    LOGIN ='https://trader.degiro.nl/login/secure/login'
    ORDER_CHECK = 'https://trader.degiro.nl/trading/secure/v5/checkOrder'
    ORDER_CONFIRM = 'https://trader.degiro.nl/trading/secure/v5/order'
    ORDER_DELETE = 'https://trader.degiro.nl/trading/secure/v5/order'
    ORDERS_HISTORY = 'https://trader.degiro.nl/reporting/secure/v4/order-history'
    ORDER_UPDATE = 'https://trader.degiro.nl/trading/secure/v5/order'
    PRODUCT_FAVOURITES_LISTS = 'https://trader.degiro.nl/pa/secure/favourites/lists' #?intAccount=xxxxxxxx&sessionId=FA57111F85C5EE988A7C402F346A311C.prod_a_112_2
    PRODUCT_SEARCH_BONDS = 'https://trader.degiro.nl/product_search/secure/v5/bonds'
    PRODUCT_SEARCH_ETFS = 'https://trader.degiro.nl/product_search/secure/v5/etfs'
    PRODUCT_SEARCH_FUNDS = 'https://trader.degiro.nl/product_search/secure/v5/funds'
    PRODUCT_SEARCH_FUTURES = 'https://trader.degiro.nl/product_search/secure/v5/futures'
    PRODUCT_SEARCH_LEVERAGEDS = 'https://trader.degiro.nl/product_search/secure/v5/leverageds'
    PRODUCT_SEARCH_LOOKUP = 'https://trader.degiro.nl/product_search/secure/v5/products/lookup'
    PRODUCT_SEARCH_OPTIONS = 'https://trader.degiro.nl/product_search/secure/v5/options'
    PRODUCT_SEARCH_STOCKS = 'https://trader.degiro.nl/product_search/secure/v5/stocks'
    PRODUCT_SEARCH_WARRANTS = 'https://trader.degiro.nl/product_search/secure/v5/warrants'
    TRANSACTIONS_HISTORY = 'https://trader.degiro.nl/reporting/secure/v4/transactions'
    UPDATE = 'https://trader.degiro.nl/trading/secure/v5/update'