"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import degiro_connector.trading.models.trading_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CREDENTIALS_FIELD_NUMBER: builtins.int
    AUTO_CONNECT_FIELD_NUMBER: builtins.int
    @property
    def credentials(self) -> degiro_connector.trading.models.trading_pb2.Credentials: ...
    auto_connect: builtins.bool = ...
    def __init__(self,
        *,
        credentials : typing.Optional[degiro_connector.trading.models.trading_pb2.Credentials] = ...,
        auto_connect : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"credentials",b"credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"auto_connect",b"auto_connect",u"credentials",b"credentials"]) -> None: ...
global___Config = Config

class ConfirmationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONFIRMATION_ID_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    confirmation_id: typing.Text = ...
    @property
    def order(self) -> degiro_connector.trading.models.trading_pb2.Order: ...
    def __init__(self,
        *,
        confirmation_id : typing.Text = ...,
        order : typing.Optional[degiro_connector.trading.models.trading_pb2.Order] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"order",b"order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"confirmation_id",b"confirmation_id",u"order",b"order"]) -> None: ...
global___ConfirmationRequest = ConfirmationRequest
