"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Credentials(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT_ACCOUNT_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    TOTP_SECRET_KEY_FIELD_NUMBER: builtins.int
    ONE_TIME_PASSWORD_FIELD_NUMBER: builtins.int
    int_account: builtins.int
    username: builtins.str
    password: builtins.str
    totp_secret_key: builtins.str
    one_time_password: builtins.int
    def __init__(
        self,
        *,
        int_account: builtins.int = ...,
        username: builtins.str = ...,
        password: builtins.str = ...,
        totp_secret_key: builtins.str = ...,
        one_time_password: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["one_time_password", b"one_time_password", "oneof_2fa", b"oneof_2fa", "totp_secret_key", b"totp_secret_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["int_account", b"int_account", "one_time_password", b"one_time_password", "oneof_2fa", b"oneof_2fa", "password", b"password", "totp_secret_key", b"totp_secret_key", "username", b"username"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["oneof_2fa", b"oneof_2fa"]) -> typing_extensions.Literal["totp_secret_key", "one_time_password"] | None: ...

global___Credentials = Credentials

@typing_extensions.final
class Order(google.protobuf.message.Message):
    """* For the payload from the following URLs :
    https://trader.degiro.nl/trading/secure/v5/checkOrder
    https://trader.degiro.nl/trading/secure/v5/order
    https://trader.degiro.nl/reporting/secure/v4/order-history
    https://trader.degiro.nl/trading/secure/v5/update
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Action:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Order._Action.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BUY: Order._Action.ValueType  # 0
        SELL: Order._Action.ValueType  # 1

    class Action(_Action, metaclass=_ActionEnumTypeWrapper):
        """ENUMS"""

    BUY: Order.Action.ValueType  # 0
    SELL: Order.Action.ValueType  # 1

    class _OrderType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OrderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Order._OrderType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LIMIT: Order._OrderType.ValueType  # 0
        STOP_LIMIT: Order._OrderType.ValueType  # 1
        MARKET: Order._OrderType.ValueType  # 2
        STOP_LOSS: Order._OrderType.ValueType  # 3
        """*
        LIMIT_HIT = ?;
        TRAILING_STOP = ?;
        JOIN = ?;
        STANDARD_SIZE = ?;
        STANDARD_AMOUNT = ?;
        TAKE_PROFIT = ?;
        COMBINED = ?;
        OCO = ?;
        """

    class OrderType(_OrderType, metaclass=_OrderTypeEnumTypeWrapper): ...
    LIMIT: Order.OrderType.ValueType  # 0
    STOP_LIMIT: Order.OrderType.ValueType  # 1
    MARKET: Order.OrderType.ValueType  # 2
    STOP_LOSS: Order.OrderType.ValueType  # 3
    """*
    LIMIT_HIT = ?;
    TRAILING_STOP = ?;
    JOIN = ?;
    STANDARD_SIZE = ?;
    STANDARD_AMOUNT = ?;
    TAKE_PROFIT = ?;
    COMBINED = ?;
    OCO = ?;
    """

    class _TimeType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TimeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Order._TimeType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_0: Order._TimeType.ValueType  # 0
        GOOD_TILL_DAY: Order._TimeType.ValueType  # 1
        UNKNOWN_2: Order._TimeType.ValueType  # 2
        GOOD_TILL_CANCELED: Order._TimeType.ValueType  # 3

    class TimeType(_TimeType, metaclass=_TimeTypeEnumTypeWrapper): ...
    UNKNOWN_0: Order.TimeType.ValueType  # 0
    GOOD_TILL_DAY: Order.TimeType.ValueType  # 1
    UNKNOWN_2: Order.TimeType.ValueType  # 2
    GOOD_TILL_CANCELED: Order.TimeType.ValueType  # 3

    @typing_extensions.final
    class CheckingResponse(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONFIRMATION_ID_FIELD_NUMBER: builtins.int
        FREE_SPACE_NEW_FIELD_NUMBER: builtins.int
        RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
        TRANSACTION_FEES_FIELD_NUMBER: builtins.int
        TRANSACTION_OPPOSITE_FEES_FIELD_NUMBER: builtins.int
        TRANSACTION_TAXES_FIELD_NUMBER: builtins.int
        TRANSACTION_AUTO_FX_SURCHARGES_FIELD_NUMBER: builtins.int
        TRANSACTION_AUTO_FX_OPPOSITE_SURCHARGES_FIELD_NUMBER: builtins.int
        AUTO_FX_CONVERSION_RATE_FIELD_NUMBER: builtins.int
        TRANSACTION_FEE_FIELD_NUMBER: builtins.int
        SHOW_EX_ANTE_REPORT_LINK_FIELD_NUMBER: builtins.int
        confirmation_id: builtins.str
        free_space_new: builtins.float
        @property
        def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def transaction_fees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def transaction_opposite_fees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def transaction_taxes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def transaction_auto_fx_surcharges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def transaction_auto_fx_opposite_surcharges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        auto_fx_conversion_rate: builtins.float
        transaction_fee: builtins.float
        show_ex_ante_report_link: builtins.bool
        def __init__(
            self,
            *,
            confirmation_id: builtins.str = ...,
            free_space_new: builtins.float = ...,
            response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            transaction_fees: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            transaction_opposite_fees: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            transaction_taxes: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            transaction_auto_fx_surcharges: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            transaction_auto_fx_opposite_surcharges: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            auto_fx_conversion_rate: builtins.float = ...,
            transaction_fee: builtins.float = ...,
            show_ex_ante_report_link: builtins.bool = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["auto_fx_conversion_rate", b"auto_fx_conversion_rate", "confirmation_id", b"confirmation_id", "free_space_new", b"free_space_new", "response_datetime", b"response_datetime", "show_ex_ante_report_link", b"show_ex_ante_report_link", "transaction_auto_fx_opposite_surcharges", b"transaction_auto_fx_opposite_surcharges", "transaction_auto_fx_surcharges", b"transaction_auto_fx_surcharges", "transaction_fee", b"transaction_fee", "transaction_fees", b"transaction_fees", "transaction_opposite_fees", b"transaction_opposite_fees", "transaction_taxes", b"transaction_taxes"]) -> None: ...

    @typing_extensions.final
    class ConfirmationResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ORDER_ID_FIELD_NUMBER: builtins.int
        RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
        order_id: builtins.str
        @property
        def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            order_id: builtins.str = ...,
            response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["order_id", b"order_id", "response_datetime", b"response_datetime"]) -> None: ...

    ACTION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    ORDER_TYPE_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    STOP_PRICE_FIELD_NUMBER: builtins.int
    PRODUCT_ID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    TIME_TYPE_FIELD_NUMBER: builtins.int
    CONTRACT_SIZE_FIELD_NUMBER: builtins.int
    CONTRACT_TYPE_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    HOUR_FIELD_NUMBER: builtins.int
    IS_DELETABLE_FIELD_NUMBER: builtins.int
    IS_MODIFIABLE_FIELD_NUMBER: builtins.int
    PRODUCT_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    TOTAL_ORDER_VALUE_FIELD_NUMBER: builtins.int
    RETAINED_ORDER_FIELD_NUMBER: builtins.int
    SENT_TO_EXCHANGE_FIELD_NUMBER: builtins.int
    action: global___Order.Action.ValueType
    """USED TO CHECK ORDER
    called "buysell" by the API
    """
    id: builtins.str
    order_type: global___Order.OrderType.ValueType
    """called "orderTypeId" by the API"""
    price: builtins.float
    stop_price: builtins.float
    """called "stopPrice" by the API"""
    product_id: builtins.int
    """called "productId" by the API"""
    size: builtins.float
    time_type: global___Order.TimeType.ValueType
    """called "orderTimeTypeId" by the API"""
    contract_size: builtins.float
    """USED TO CONFIRM ORDER
    called "contractSize" by the API
    """
    contract_type: builtins.int
    """called "contractType" by the API"""
    currency: builtins.str
    hour: builtins.str
    """called "date" by the API"""
    is_deletable: builtins.bool
    """contains %H:%M if the date was not passed
    called "isDeletable" by the API
    """
    is_modifiable: builtins.bool
    """called "isModifiable" by the API"""
    product: builtins.str
    quantity: builtins.float
    total_order_value: builtins.float
    """called "totalOrderValue" by the API"""
    retained_order: builtins.bool
    """USED FOR ORDERS HISTORY
    called "retainedOrder" by the API
    """
    sent_to_exchange: builtins.bool
    """called "sentToExchange" by the API"""
    def __init__(
        self,
        *,
        action: global___Order.Action.ValueType = ...,
        id: builtins.str = ...,
        order_type: global___Order.OrderType.ValueType = ...,
        price: builtins.float = ...,
        stop_price: builtins.float = ...,
        product_id: builtins.int = ...,
        size: builtins.float = ...,
        time_type: global___Order.TimeType.ValueType = ...,
        contract_size: builtins.float = ...,
        contract_type: builtins.int = ...,
        currency: builtins.str = ...,
        hour: builtins.str = ...,
        is_deletable: builtins.bool = ...,
        is_modifiable: builtins.bool = ...,
        product: builtins.str = ...,
        quantity: builtins.float = ...,
        total_order_value: builtins.float = ...,
        retained_order: builtins.bool = ...,
        sent_to_exchange: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["action", b"action", "contract_size", b"contract_size", "contract_type", b"contract_type", "currency", b"currency", "hour", b"hour", "id", b"id", "is_deletable", b"is_deletable", "is_modifiable", b"is_modifiable", "order_type", b"order_type", "price", b"price", "product", b"product", "product_id", b"product_id", "quantity", b"quantity", "retained_order", b"retained_order", "sent_to_exchange", b"sent_to_exchange", "size", b"size", "stop_price", b"stop_price", "time_type", b"time_type", "total_order_value", b"total_order_value"]) -> None: ...

global___Order = Order

@typing_extensions.final
class Update(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/trading/secure/v5/update
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Option:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OptionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Update._Option.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ALERTS: Update._Option.ValueType  # 0
        CASHFUNDS: Update._Option.ValueType  # 1
        HISTORICALORDERS: Update._Option.ValueType  # 2
        ORDERS: Update._Option.ValueType  # 3
        PORTFOLIO: Update._Option.ValueType  # 4
        TOTALPORTFOLIO: Update._Option.ValueType  # 5
        TRANSACTIONS: Update._Option.ValueType  # 6

    class Option(_Option, metaclass=_OptionEnumTypeWrapper):
        """ENUMS"""

    ALERTS: Update.Option.ValueType  # 0
    CASHFUNDS: Update.Option.ValueType  # 1
    HISTORICALORDERS: Update.Option.ValueType  # 2
    ORDERS: Update.Option.ValueType  # 3
    PORTFOLIO: Update.Option.ValueType  # 4
    TOTALPORTFOLIO: Update.Option.ValueType  # 5
    TRANSACTIONS: Update.Option.ValueType  # 6

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OPTION_FIELD_NUMBER: builtins.int
        LAST_UPDATED_FIELD_NUMBER: builtins.int
        option: global___Update.Option.ValueType
        last_updated: builtins.int
        def __init__(
            self,
            *,
            option: global___Update.Option.ValueType = ...,
            last_updated: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "option", b"option"]) -> None: ...

    @typing_extensions.final
    class RequestList(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUES_FIELD_NUMBER: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Update.Request]: ...
        def __init__(
            self,
            *,
            values: collections.abc.Iterable[global___Update.Request] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

    @typing_extensions.final
    class Alerts(google.protobuf.message.Message):
        """MESSAGES FOR PROPERTIES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class CashFunds(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class HistoricalOrders(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Order]: ...
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: collections.abc.Iterable[global___Order] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class Orders(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Order]:
            """Order"""
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: collections.abc.Iterable[global___Order] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class Portfolio(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
            """positionrow"""
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class TotalPortfolio(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    @typing_extensions.final
    class Transactions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LAST_UPDATED_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        last_updated: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
            """Transaction"""
        def __init__(
            self,
            *,
            last_updated: builtins.int = ...,
            values: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["last_updated", b"last_updated", "values", b"values"]) -> None: ...

    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    ALERTS_FIELD_NUMBER: builtins.int
    CASH_FUNDS_FIELD_NUMBER: builtins.int
    HISTORICAL_ORDERS_FIELD_NUMBER: builtins.int
    ORDERS_FIELD_NUMBER: builtins.int
    PORTFOLIO_FIELD_NUMBER: builtins.int
    TOTAL_PORTFOLIO_FIELD_NUMBER: builtins.int
    TRANSACTIONS_FIELD_NUMBER: builtins.int
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """PROPERTIES"""
    @property
    def alerts(self) -> global___Update.Alerts: ...
    @property
    def cash_funds(self) -> global___Update.CashFunds: ...
    @property
    def historical_orders(self) -> global___Update.HistoricalOrders: ...
    @property
    def orders(self) -> global___Update.Orders: ...
    @property
    def portfolio(self) -> global___Update.Portfolio: ...
    @property
    def total_portfolio(self) -> global___Update.TotalPortfolio: ...
    @property
    def transactions(self) -> global___Update.Transactions: ...
    def __init__(
        self,
        *,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        alerts: global___Update.Alerts | None = ...,
        cash_funds: global___Update.CashFunds | None = ...,
        historical_orders: global___Update.HistoricalOrders | None = ...,
        orders: global___Update.Orders | None = ...,
        portfolio: global___Update.Portfolio | None = ...,
        total_portfolio: global___Update.TotalPortfolio | None = ...,
        transactions: global___Update.Transactions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["alerts", b"alerts", "cash_funds", b"cash_funds", "historical_orders", b"historical_orders", "orders", b"orders", "portfolio", b"portfolio", "response_datetime", b"response_datetime", "total_portfolio", b"total_portfolio", "transactions", b"transactions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alerts", b"alerts", "cash_funds", b"cash_funds", "historical_orders", b"historical_orders", "orders", b"orders", "portfolio", b"portfolio", "response_datetime", b"response_datetime", "total_portfolio", b"total_portfolio", "transactions", b"transactions"]) -> None: ...

global___Update = Update

@typing_extensions.final
class OrdersHistory(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/reporting/secure/v4/order-history
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class Date(google.protobuf.message.Message):
            """MESSAGES"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            YEAR_FIELD_NUMBER: builtins.int
            MONTH_FIELD_NUMBER: builtins.int
            DAY_FIELD_NUMBER: builtins.int
            year: builtins.int
            month: builtins.int
            day: builtins.int
            def __init__(
                self,
                *,
                year: builtins.int = ...,
                month: builtins.int = ...,
                day: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["day", b"day", "month", b"month", "year", b"year"]) -> None: ...

        FROM_DATE_FIELD_NUMBER: builtins.int
        TO_DATE_FIELD_NUMBER: builtins.int
        @property
        def from_date(self) -> global___OrdersHistory.Request.Date:
            """PROPERTIES"""
        @property
        def to_date(self) -> global___OrdersHistory.Request.Date: ...
        def __init__(
            self,
            *,
            from_date: global___OrdersHistory.Request.Date | None = ...,
            to_date: global___OrdersHistory.Request.Date | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime", "values", b"values"]) -> None: ...

global___OrdersHistory = OrdersHistory

@typing_extensions.final
class TransactionsHistory(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/reporting/secure/v4/transactions
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class Date(google.protobuf.message.Message):
            """MESSAGES"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            YEAR_FIELD_NUMBER: builtins.int
            MONTH_FIELD_NUMBER: builtins.int
            DAY_FIELD_NUMBER: builtins.int
            year: builtins.int
            month: builtins.int
            day: builtins.int
            def __init__(
                self,
                *,
                year: builtins.int = ...,
                month: builtins.int = ...,
                day: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["day", b"day", "month", b"month", "year", b"year"]) -> None: ...

        FROM_DATE_FIELD_NUMBER: builtins.int
        TO_DATE_FIELD_NUMBER: builtins.int
        GROUP_TRANSACTIONS_BY_ORDER_FIELD_NUMBER: builtins.int
        @property
        def from_date(self) -> global___TransactionsHistory.Request.Date:
            """PROPERTIES"""
        @property
        def to_date(self) -> global___TransactionsHistory.Request.Date: ...
        group_transactions_by_order: builtins.bool
        def __init__(
            self,
            *,
            from_date: global___TransactionsHistory.Request.Date | None = ...,
            to_date: global___TransactionsHistory.Request.Date | None = ...,
            group_transactions_by_order: builtins.bool = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "group_transactions_by_order", b"group_transactions_by_order", "to_date", b"to_date"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime", "values", b"values"]) -> None: ...

global___TransactionsHistory = TransactionsHistory

@typing_extensions.final
class AccountOverview(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/reporting/secure/v6/accountoverview
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class Date(google.protobuf.message.Message):
            """MESSAGES"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            YEAR_FIELD_NUMBER: builtins.int
            MONTH_FIELD_NUMBER: builtins.int
            DAY_FIELD_NUMBER: builtins.int
            year: builtins.int
            month: builtins.int
            day: builtins.int
            def __init__(
                self,
                *,
                year: builtins.int = ...,
                month: builtins.int = ...,
                day: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["day", b"day", "month", b"month", "year", b"year"]) -> None: ...

        FROM_DATE_FIELD_NUMBER: builtins.int
        TO_DATE_FIELD_NUMBER: builtins.int
        @property
        def from_date(self) -> global___AccountOverview.Request.Date:
            """PROPERTIES"""
        @property
        def to_date(self) -> global___AccountOverview.Request.Date: ...
        def __init__(
            self,
            *,
            from_date: global___AccountOverview.Request.Date | None = ...,
            to_date: global___AccountOverview.Request.Date | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.struct_pb2.Struct:
        """PROPERTIES"""
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        values: google.protobuf.struct_pb2.Struct | None = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime", "values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime", "values", b"values"]) -> None: ...

global___AccountOverview = AccountOverview

@typing_extensions.final
class ProductSearch(google.protobuf.message.Message):
    """* For the payload from the following URLs :
    https://trader.degiro.nl/product_search/secure/v5/bonds
    https://trader.degiro.nl/product_search/secure/v5/etfs
    https://trader.degiro.nl/product_search/secure/v5/funds
    https://trader.degiro.nl/product_search/secure/v5/futures
    https://trader.degiro.nl/product_search/secure/v5/leverageds
    https://trader.degiro.nl/product_search/secure/v5/lookup
    https://trader.degiro.nl/product_search/secure/v5/options
    https://trader.degiro.nl/product_search/secure/v5/stocks
    https://trader.degiro.nl/product_search/secure/v5/warrants
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Config(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUES_FIELD_NUMBER: builtins.int
        @property
        def values(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            values: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

    @typing_extensions.final
    class RequestBonds(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BOND_ISSUER_TYPE_ID_FIELD_NUMBER: builtins.int
        BOND_EXCHANGE_ID_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        bond_issuer_type_id: builtins.int
        bond_exchange_id: builtins.int
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            bond_issuer_type_id: builtins.int = ...,
            bond_exchange_id: builtins.int = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["bond_exchange_id", b"bond_exchange_id", "bond_issuer_type_id", b"bond_issuer_type_id", "limit", b"limit", "offset", b"offset", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types"]) -> None: ...

    @typing_extensions.final
    class RequestETFs(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POPULAR_ONLY_FIELD_NUMBER: builtins.int
        INPUT_AGGREGATE_TYPES_FIELD_NUMBER: builtins.int
        INPUT_AGGREGATE_VALUES_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        popular_only: builtins.bool
        input_aggregate_types: builtins.str
        input_aggregate_values: builtins.str
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            popular_only: builtins.bool = ...,
            input_aggregate_types: builtins.str = ...,
            input_aggregate_values: builtins.str = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["input_aggregate_types", b"input_aggregate_types", "input_aggregate_values", b"input_aggregate_values", "limit", b"limit", "offset", b"offset", "popular_only", b"popular_only", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types"]) -> None: ...

    @typing_extensions.final
    class RequestFunds(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["limit", b"limit", "offset", b"offset", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types"]) -> None: ...

    @typing_extensions.final
    class RequestFutures(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FUTURE_EXCHANGE_ID_FIELD_NUMBER: builtins.int
        UNDERLYING_ISIN_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        future_exchange_id: builtins.int
        underlying_isin: builtins.str
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            future_exchange_id: builtins.int = ...,
            underlying_isin: builtins.str = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["future_exchange_id", b"future_exchange_id", "limit", b"limit", "offset", b"offset", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types", "underlying_isin", b"underlying_isin"]) -> None: ...

    @typing_extensions.final
    class RequestLeverageds(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POPULAR_ONLY_FIELD_NUMBER: builtins.int
        INPUT_AGGREGATE_TYPES_FIELD_NUMBER: builtins.int
        INPUT_AGGREGATE_VALUES_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        popular_only: builtins.bool
        input_aggregate_types: builtins.str
        input_aggregate_values: builtins.str
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            popular_only: builtins.bool = ...,
            input_aggregate_types: builtins.str = ...,
            input_aggregate_values: builtins.str = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["input_aggregate_types", b"input_aggregate_types", "input_aggregate_values", b"input_aggregate_values", "limit", b"limit", "offset", b"offset", "popular_only", b"popular_only", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types"]) -> None: ...

    @typing_extensions.final
    class RequestLookup(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        PRODUCT_TYPE_ID_FIELD_NUMBER: builtins.int
        search_text: builtins.str
        limit: builtins.int
        offset: builtins.int
        product_type_id: builtins.int
        def __init__(
            self,
            *,
            search_text: builtins.str = ...,
            limit: builtins.int = ...,
            offset: builtins.int = ...,
            product_type_id: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["limit", b"limit", "offset", b"offset", "product_type_id", b"product_type_id", "search_text", b"search_text"]) -> None: ...

    @typing_extensions.final
    class RequestOptions(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INPUT_AGGREGATE_TYPES_FIELD_NUMBER: builtins.int
        INPUT_AGGREGATE_VALUES_FIELD_NUMBER: builtins.int
        OPTION_EXCHANGE_ID_FIELD_NUMBER: builtins.int
        UNDERLYING_ISIN_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        input_aggregate_types: builtins.str
        input_aggregate_values: builtins.str
        option_exchange_id: builtins.int
        underlying_isin: builtins.str
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            input_aggregate_types: builtins.str = ...,
            input_aggregate_values: builtins.str = ...,
            option_exchange_id: builtins.int = ...,
            underlying_isin: builtins.str = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["input_aggregate_types", b"input_aggregate_types", "input_aggregate_values", b"input_aggregate_values", "limit", b"limit", "offset", b"offset", "option_exchange_id", b"option_exchange_id", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types", "underlying_isin", b"underlying_isin"]) -> None: ...

    @typing_extensions.final
    class RequestStocks(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_IN_US_GREEN_LIST_FIELD_NUMBER: builtins.int
        INDEX_ID_FIELD_NUMBER: builtins.int
        EXCHANGE_ID_FIELD_NUMBER: builtins.int
        STOCK_COUNTRY_ID_FIELD_NUMBER: builtins.int
        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        is_in_us_green_list: builtins.bool
        index_id: builtins.int
        exchange_id: builtins.int
        stock_country_id: builtins.int
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            is_in_us_green_list: builtins.bool = ...,
            index_id: builtins.int = ...,
            exchange_id: builtins.int = ...,
            stock_country_id: builtins.int = ...,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["exchange_id", b"exchange_id", "index_id", b"index_id", "is_in_us_green_list", b"is_in_us_green_list", "limit", b"limit", "offset", b"offset", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types", "stock_country_id", b"stock_country_id"]) -> None: ...

    @typing_extensions.final
    class RequestWarrants(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SEARCH_TEXT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REQUIRE_TOTAL_FIELD_NUMBER: builtins.int
        SORT_COLUMNS_FIELD_NUMBER: builtins.int
        SORT_TYPES_FIELD_NUMBER: builtins.int
        search_text: builtins.str
        offset: builtins.int
        limit: builtins.int
        require_total: builtins.bool
        sort_columns: builtins.str
        sort_types: builtins.str
        def __init__(
            self,
            *,
            search_text: builtins.str = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            require_total: builtins.bool = ...,
            sort_columns: builtins.str = ...,
            sort_types: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["limit", b"limit", "offset", b"offset", "require_total", b"require_total", "search_text", b"search_text", "sort_columns", b"sort_columns", "sort_types", b"sort_types"]) -> None: ...

    OFFSET_FIELD_NUMBER: builtins.int
    PRODUCTS_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    offset: builtins.int
    """PROPERTIES"""
    @property
    def products(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    total: builtins.int
    def __init__(
        self,
        *,
        offset: builtins.int = ...,
        products: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        total: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["offset", b"offset", "products", b"products", "response_datetime", b"response_datetime", "total", b"total"]) -> None: ...

global___ProductSearch = ProductSearch

@typing_extensions.final
class Favourites(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/pa/secure/favourites/lists
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class List(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        IS_DEFAULT_FIELD_NUMBER: builtins.int
        PRODUCT_IDS_FIELD_NUMBER: builtins.int
        id: builtins.int
        """PROPERTIES"""
        name: builtins.str
        is_default: builtins.bool
        @property
        def product_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            id: builtins.int = ...,
            name: builtins.str = ...,
            is_default: builtins.bool = ...,
            product_ids: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "is_default", b"is_default", "name", b"name", "product_ids", b"product_ids"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Favourites.List]:
        """PROPERTIES"""
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___Favourites.List] | None = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime", "values", b"values"]) -> None: ...

global___Favourites = Favourites

@typing_extensions.final
class ProductsInfo(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/product_search/secure/v5/products/info
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRODUCTS_FIELD_NUMBER: builtins.int
        @property
        def products(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
            """PROPERTIES"""
        def __init__(
            self,
            *,
            products: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["products", b"products"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.struct_pb2.Struct:
        """PROPERTIES"""
    def __init__(
        self,
        *,
        values: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ProductsInfo = ProductsInfo

@typing_extensions.final
class CompanyRatios(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/company-ratios
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.struct_pb2.Struct:
        """PROPERTIES"""
    def __init__(
        self,
        *,
        values: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___CompanyRatios = CompanyRatios

@typing_extensions.final
class CompanyProfile(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/company-profile/v2
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.struct_pb2.Struct:
        """PROPERTIES"""
    def __init__(
        self,
        *,
        values: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___CompanyProfile = CompanyProfile

@typing_extensions.final
class FinancialStatements(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/financial-statements
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.struct_pb2.Struct:
        """PROPERTIES"""
    def __init__(
        self,
        *,
        values: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___FinancialStatements = FinancialStatements

@typing_extensions.final
class LatestNews(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/newsfeed/v2/latest-news
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OFFSET_FIELD_NUMBER: builtins.int
        LANGUAGES_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        offset: builtins.int
        """PROPERTIES"""
        languages: builtins.str
        limit: builtins.int
        def __init__(
            self,
            *,
            offset: builtins.int = ...,
            languages: builtins.str = ...,
            limit: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["languages", b"languages", "limit", b"limit", "offset", b"offset"]) -> None: ...

    ITEMS_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    offset: builtins.int
    total: builtins.int
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        offset: builtins.int = ...,
        total: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["items", b"items", "offset", b"offset", "total", b"total"]) -> None: ...

global___LatestNews = LatestNews

@typing_extensions.final
class TopNewsPreview(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/newsfeed/v2/top-news-preview
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    offset: builtins.int
    total: builtins.int
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        offset: builtins.int = ...,
        total: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["items", b"items", "offset", b"offset", "total", b"total"]) -> None: ...

global___TopNewsPreview = TopNewsPreview

@typing_extensions.final
class NewsByCompany(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/newsfeed/v2/news-by-company
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ISIN_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LANGUAGES_FIELD_NUMBER: builtins.int
        isin: builtins.str
        """PROPERTIES"""
        limit: builtins.int
        offset: builtins.int
        languages: builtins.str
        def __init__(
            self,
            *,
            isin: builtins.str = ...,
            limit: builtins.int = ...,
            offset: builtins.int = ...,
            languages: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["isin", b"isin", "languages", b"languages", "limit", b"limit", "offset", b"offset"]) -> None: ...

    ITEMS_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    offset: builtins.int
    total: builtins.int
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        offset: builtins.int = ...,
        total: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["items", b"items", "offset", b"offset", "total", b"total"]) -> None: ...

global___NewsByCompany = NewsByCompany

@typing_extensions.final
class CashAccountReport(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/reporting/secure/v3/cashAccountReport
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CashAccountReport._Format.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CSV: CashAccountReport._Format.ValueType  # 0
        HTML: CashAccountReport._Format.ValueType  # 1
        PDF: CashAccountReport._Format.ValueType  # 2
        XLS: CashAccountReport._Format.ValueType  # 3

    class Format(_Format, metaclass=_FormatEnumTypeWrapper):
        """ENUMS"""

    CSV: CashAccountReport.Format.ValueType  # 0
    HTML: CashAccountReport.Format.ValueType  # 1
    PDF: CashAccountReport.Format.ValueType  # 2
    XLS: CashAccountReport.Format.ValueType  # 3

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class Date(google.protobuf.message.Message):
            """MESSAGES"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            YEAR_FIELD_NUMBER: builtins.int
            MONTH_FIELD_NUMBER: builtins.int
            DAY_FIELD_NUMBER: builtins.int
            year: builtins.int
            month: builtins.int
            day: builtins.int
            def __init__(
                self,
                *,
                year: builtins.int = ...,
                month: builtins.int = ...,
                day: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["day", b"day", "month", b"month", "year", b"year"]) -> None: ...

        FORMAT_FIELD_NUMBER: builtins.int
        COUNTRY_FIELD_NUMBER: builtins.int
        LANG_FIELD_NUMBER: builtins.int
        FROM_DATE_FIELD_NUMBER: builtins.int
        TO_DATE_FIELD_NUMBER: builtins.int
        format: global___CashAccountReport.Format.ValueType
        """PROPERTIES"""
        country: builtins.str
        lang: builtins.str
        @property
        def from_date(self) -> global___CashAccountReport.Request.Date: ...
        @property
        def to_date(self) -> global___CashAccountReport.Request.Date: ...
        def __init__(
            self,
            *,
            format: global___CashAccountReport.Format.ValueType = ...,
            country: builtins.str = ...,
            lang: builtins.str = ...,
            from_date: global___CashAccountReport.Request.Date | None = ...,
            to_date: global___CashAccountReport.Request.Date | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["from_date", b"from_date", "to_date", b"to_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["country", b"country", "format", b"format", "from_date", b"from_date", "lang", b"lang", "to_date", b"to_date"]) -> None: ...

    CONTENT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    content: builtins.str
    """PROPERTIES"""
    format: global___CashAccountReport.Format.ValueType
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        format: global___CashAccountReport.Format.ValueType = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["content", b"content", "format", b"format", "response_datetime", b"response_datetime"]) -> None: ...

global___CashAccountReport = CashAccountReport

@typing_extensions.final
class Agenda(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/dgtbxdsservice/agenda/v2
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _CalendarType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CalendarTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Agenda._CalendarType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DIVIDEND_CALENDAR: Agenda._CalendarType.ValueType  # 0
        ECONOMIC_CALENDAR: Agenda._CalendarType.ValueType  # 1
        EARNINGS_CALENDAR: Agenda._CalendarType.ValueType  # 2
        HOLIDAY_CALENDAR: Agenda._CalendarType.ValueType  # 3
        IPO_CALENDAR: Agenda._CalendarType.ValueType  # 4
        SPLIT_CALENDAR: Agenda._CalendarType.ValueType  # 5

    class CalendarType(_CalendarType, metaclass=_CalendarTypeEnumTypeWrapper):
        """ENUMS"""

    DIVIDEND_CALENDAR: Agenda.CalendarType.ValueType  # 0
    ECONOMIC_CALENDAR: Agenda.CalendarType.ValueType  # 1
    EARNINGS_CALENDAR: Agenda.CalendarType.ValueType  # 2
    HOLIDAY_CALENDAR: Agenda.CalendarType.ValueType  # 3
    IPO_CALENDAR: Agenda.CalendarType.ValueType  # 4
    SPLIT_CALENDAR: Agenda.CalendarType.ValueType  # 5

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CALENDAR_TYPE_FIELD_NUMBER: builtins.int
        OFFSET_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        ORDER_BY_DESC_FIELD_NUMBER: builtins.int
        START_DATE_FIELD_NUMBER: builtins.int
        END_DATE_FIELD_NUMBER: builtins.int
        COMPANY_NAME_FIELD_NUMBER: builtins.int
        COUNTRIES_FIELD_NUMBER: builtins.int
        CLASSIFICATIONS_FIELD_NUMBER: builtins.int
        UNITS_FIELD_NUMBER: builtins.int
        calendar_type: global___Agenda.CalendarType.ValueType
        """PROPERTIES"""
        offset: builtins.int
        limit: builtins.int
        order_by_desc: builtins.bool
        @property
        def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        company_name: builtins.str
        countries: builtins.str
        classifications: builtins.str
        units: builtins.str
        def __init__(
            self,
            *,
            calendar_type: global___Agenda.CalendarType.ValueType = ...,
            offset: builtins.int = ...,
            limit: builtins.int = ...,
            order_by_desc: builtins.bool = ...,
            start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            company_name: builtins.str = ...,
            countries: builtins.str = ...,
            classifications: builtins.str = ...,
            units: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["end_date", b"end_date", "start_date", b"start_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["calendar_type", b"calendar_type", "classifications", b"classifications", "company_name", b"company_name", "countries", b"countries", "end_date", b"end_date", "limit", b"limit", "offset", b"offset", "order_by_desc", b"order_by_desc", "start_date", b"start_date", "units", b"units"]) -> None: ...

    CALENDAR_TYPE_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    calendar_type: global___Agenda.CalendarType.ValueType
    """PROPERTIES"""
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    offset: builtins.int
    total: builtins.int
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        calendar_type: global___Agenda.CalendarType.ValueType = ...,
        items: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        offset: builtins.int = ...,
        total: builtins.int = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["calendar_type", b"calendar_type", "items", b"items", "offset", b"offset", "response_datetime", b"response_datetime", "total", b"total"]) -> None: ...

global___Agenda = Agenda

@typing_extensions.final
class EstimatesSummaries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANNUAL_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    INTERIM_FIELD_NUMBER: builtins.int
    LASTRETRIEVED_FIELD_NUMBER: builtins.int
    LASTUPDATED_FIELD_NUMBER: builtins.int
    PREFERREDMEASURE_FIELD_NUMBER: builtins.int
    RIC_FIELD_NUMBER: builtins.int
    @property
    def annual(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]:
        """PROPERTIES"""
    currency: builtins.str
    @property
    def interim(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    lastRetrieved: builtins.str
    lastUpdated: builtins.str
    preferredMeasure: builtins.str
    ric: builtins.str
    def __init__(
        self,
        *,
        annual: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        currency: builtins.str = ...,
        interim: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        lastRetrieved: builtins.str = ...,
        lastUpdated: builtins.str = ...,
        preferredMeasure: builtins.str = ...,
        ric: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["annual", b"annual", "currency", b"currency", "interim", b"interim", "lastRetrieved", b"lastRetrieved", "lastUpdated", b"lastUpdated", "preferredMeasure", b"preferredMeasure", "ric", b"ric"]) -> None: ...

global___EstimatesSummaries = EstimatesSummaries

@typing_extensions.final
class PositionReport(google.protobuf.message.Message):
    """* For the payload from the following URL :
    https://trader.degiro.nl/reporting/secure/v3/positionReport
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PositionReport._Format.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CSV: PositionReport._Format.ValueType  # 0
        HTML: PositionReport._Format.ValueType  # 1
        PDF: PositionReport._Format.ValueType  # 2
        XLS: PositionReport._Format.ValueType  # 3

    class Format(_Format, metaclass=_FormatEnumTypeWrapper):
        """ENUMS"""

    CSV: PositionReport.Format.ValueType  # 0
    HTML: PositionReport.Format.ValueType  # 1
    PDF: PositionReport.Format.ValueType  # 2
    XLS: PositionReport.Format.ValueType  # 3

    @typing_extensions.final
    class Request(google.protobuf.message.Message):
        """MESSAGES"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class Date(google.protobuf.message.Message):
            """MESSAGES"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            YEAR_FIELD_NUMBER: builtins.int
            MONTH_FIELD_NUMBER: builtins.int
            DAY_FIELD_NUMBER: builtins.int
            year: builtins.int
            month: builtins.int
            day: builtins.int
            def __init__(
                self,
                *,
                year: builtins.int = ...,
                month: builtins.int = ...,
                day: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["day", b"day", "month", b"month", "year", b"year"]) -> None: ...

        FORMAT_FIELD_NUMBER: builtins.int
        COUNTRY_FIELD_NUMBER: builtins.int
        LANG_FIELD_NUMBER: builtins.int
        TO_DATE_FIELD_NUMBER: builtins.int
        format: global___PositionReport.Format.ValueType
        """PROPERTIES"""
        country: builtins.str
        lang: builtins.str
        @property
        def to_date(self) -> global___PositionReport.Request.Date: ...
        def __init__(
            self,
            *,
            format: global___PositionReport.Format.ValueType = ...,
            country: builtins.str = ...,
            lang: builtins.str = ...,
            to_date: global___PositionReport.Request.Date | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["to_date", b"to_date"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["country", b"country", "format", b"format", "lang", b"lang", "to_date", b"to_date"]) -> None: ...

    CONTENT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    RESPONSE_DATETIME_FIELD_NUMBER: builtins.int
    content: builtins.str
    """PROPERTIES"""
    format: global___PositionReport.Format.ValueType
    @property
    def response_datetime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        format: global___PositionReport.Format.ValueType = ...,
        response_datetime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response_datetime", b"response_datetime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["content", b"content", "format", b"format", "response_datetime", b"response_datetime"]) -> None: ...

global___PositionReport = PositionReport